apiVersion: batch/v1
kind: CronJob
metadata:
  name: my-cronjob
spec:
  schedule: "*/2 * * * *"
  jobTemplate:
    spec: 
      template:
        spec:
          containers:
          - name: busybox 
            image: busybox:latest
            command: ["echo",  "K8S Cronjob"]
          restartPolicy: Never
